# Site settings
title: Charles Zhang
description: Charles' Personal Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://charleszhang.ca" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Charles Zhang
user_description: University of Waterloo Class of 2023 | B. Computer Science, AI Specialization
user_title: Aspiring Autonomous Vehicle Software Engineer
email: cy9zhang@uwaterloo.ca
linkedin_username: charles-y-zhang
github_username:  charlesyz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about/
  - title: Tags
    url: /tags/
  - title: Series
    url: /series/

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
