version: "3.8"
services:
  node:
    image: "jekyll/jekyll:3.8"
    volumes:
      - ./:/srv/jekyll
    ports:
      - "3000:3000"
    command: /bin/bash -c "npm install && ./node_modules/gulp/bin/gulp.js"